author: vemacs
database: false
description: 'Clears the specified players'' armor inventory '
main: com.nullblock.vemacs.cleararmor.ClearArmor
name: ClearArmor
url: http://github.com/vemacs/ClearArmor
version: '1.0'
commands:
  cleararmor:
    description: 'Removes armor via a console command.'
    usage: 'Usage: /cleararmor <player>'
permissions:
   cleararmor.use:
    description: 'Allows you to clear the armor of another player.'
    default: op